# Generated by Django 4.2.9 on 2024-02-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('user_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('user_birth', models.CharField(max_length=45)),
                ('user_name', models.CharField(max_length=45)),
                ('user_gender', models.CharField(max_length=45)),
                ('user_nickname', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'user_info',
                'managed': False,
            },
        ),
    ]
