# Generated by Django 5.0.1 on 2024-02-07 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_info',
        ),
    ]
