# Generated by Django 3.2.23 on 2023-12-31 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeUserInfo',
        ),
    ]
