# Generated by Django 5.0.1 on 2024-02-26 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0003_leagueinfo_matchinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerInfo',
            fields=[
                ('user_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('player_height', models.IntegerField()),
                ('player_weight', models.IntegerField()),
                ('player_point', models.IntegerField()),
                ('player_area', models.CharField(max_length=45)),
                ('player_position', models.CharField(max_length=45)),
                ('player_description', models.CharField(max_length=200)),
                ('player_goal', models.IntegerField()),
                ('player_assist', models.IntegerField()),
                ('player_foot', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'player_info',
                'managed': False,
            },
        ),
    ]
