# Generated by Django 4.2.9 on 2024-05-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0005_v2_matchinfo_v2_teaminfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='V2_UserInfo',
            fields=[
                ('V2_user_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('V2_user_id', models.CharField(max_length=45)),
                ('V2_password', models.CharField(max_length=200)),
                ('V2_user_birth', models.CharField(max_length=45)),
                ('V2_user_name', models.CharField(max_length=45)),
                ('V2_user_gender', models.CharField(max_length=45)),
                ('V2_user_nickname', models.CharField(max_length=45)),
                ('V2_marketing_agree', models.BooleanField()),
                ('V2_login_type', models.IntegerField()),
            ],
            options={
                'db_table': 'V2_user_info',
                'managed': False,
            },
        ),
    ]
