# Generated by Django 4.0.3 on 2024-10-27 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0006_v2_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalGame',
        ),
        migrations.DeleteModel(
            name='AnalPlayer',
        ),
        migrations.DeleteModel(
            name='ARank',
        ),
        migrations.DeleteModel(
            name='GameGps',
        ),
        migrations.DeleteModel(
            name='GameInfo',
        ),
        migrations.DeleteModel(
            name='LeagueInfo',
        ),
        migrations.DeleteModel(
            name='PlayerInfo',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
