# Generated by Django 4.0.3 on 2024-11-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0007_delete_analgame_delete_analplayer_delete_arank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMatchInfo',
            fields=[
                ('match_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('match_team_code', models.CharField(blank=True, max_length=45, null=True)),
                ('match_quarter_info', models.JSONField(blank=True, null=True)),
                ('match_name', models.CharField(blank=True, max_length=45, null=True)),
                ('match_schedule', models.CharField(blank=True, max_length=45, null=True)),
                ('gps_url', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'team_match_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=200)),
                ('user_birth', models.CharField(max_length=45)),
                ('user_name', models.CharField(max_length=45)),
                ('user_gender', models.CharField(max_length=45)),
                ('user_nickname', models.CharField(max_length=45)),
                ('marketing_agree', models.BooleanField()),
                ('login_type', models.CharField(max_length=45)),
                ('user_type', models.CharField(max_length=45)),
                ('user_height', models.IntegerField()),
                ('user_weight', models.IntegerField()),
                ('user_position', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'user_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserMatch',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('match_code', models.CharField(max_length=45)),
                ('user_code', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'user_match',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserMatchInfo',
            fields=[
                ('match_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('match_quarter_info', models.JSONField(blank=True, null=True)),
                ('match_name', models.CharField(blank=True, max_length=45, null=True)),
                ('match_schedule', models.CharField(blank=True, max_length=45, null=True)),
                ('gps_url', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_match_info',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='V2_UserInfo',
        ),
    ]
