# Generated by Django 4.0.3 on 2024-12-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchInfo',
            fields=[
                ('match_code', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('match_host', models.CharField(max_length=45)),
                ('match_home', models.CharField(max_length=45)),
                ('match_away', models.CharField(max_length=45)),
                ('match_home_player', models.JSONField()),
                ('match_away_player', models.JSONField()),
                ('match_home_result', models.IntegerField()),
                ('match_away_result', models.IntegerField()),
                ('match_total_result', models.JSONField()),
                ('match_official', models.CharField(max_length=45)),
                ('match_starttime', models.CharField(max_length=45)),
                ('match_type', models.JSONField()),
                ('match_goal', models.JSONField(null=True)),
                ('match_area', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'match_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PendingInviteTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=45)),
                ('team_code', models.CharField(max_length=45)),
                ('direction', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'pending_invite_team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('team_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('team_host', models.CharField(blank=True, max_length=45, null=True)),
                ('team_logo', models.CharField(blank=True, max_length=200, null=True)),
                ('team_name', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'team_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamInfo_old',
            fields=[
                ('team_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('team_host', models.CharField(blank=True, max_length=45, null=True)),
                ('team_name', models.CharField(blank=True, max_length=45, null=True)),
                ('team_player', models.JSONField(blank=True)),
                ('team_logo', models.CharField(blank=True, max_length=45, null=True)),
                ('team_point', models.IntegerField(blank=True, null=True)),
                ('team_area', models.CharField(blank=True, max_length=45, null=True)),
                ('team_description', models.CharField(blank=True, max_length=45, null=True)),
                ('team_games', models.JSONField(blank=True)),
            ],
            options={
                'db_table': 'team_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMatchInfo',
            fields=[
                ('match_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('ground_name', models.CharField(max_length=45)),
                ('away_team', models.CharField(blank=True, max_length=45, null=True)),
                ('away_team_name', models.CharField(blank=True, max_length=45, null=True)),
                ('match_time', models.IntegerField()),
                ('match_name', models.CharField(max_length=45)),
                ('match_schedule', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'team_match_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=200)),
                ('user_birth', models.CharField(max_length=45)),
                ('user_name', models.CharField(max_length=45)),
                ('user_gender', models.CharField(max_length=45)),
                ('user_nickname', models.CharField(max_length=45)),
                ('marketing_agree', models.BooleanField(default=0)),
                ('login_type', models.CharField(max_length=45)),
                ('user_type', models.CharField(max_length=45)),
                ('user_height', models.IntegerField()),
                ('user_weight', models.IntegerField()),
                ('user_position', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'user_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_code', models.CharField(max_length=45)),
                ('user_code', models.CharField(max_length=45)),
                ('match_schedule', models.DateField()),
                ('service_type', models.CharField(max_length=20)),
                ('match_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user_match',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserMatchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_code', models.CharField(max_length=45)),
                ('user_code', models.CharField(max_length=45)),
                ('ground_name', models.CharField(max_length=45)),
                ('away_team', models.CharField(blank=True, max_length=45, null=True)),
                ('away_team_name', models.CharField(blank=True, max_length=45, null=True)),
                ('match_time', models.IntegerField(blank=True, null=True)),
                ('match_name', models.CharField(max_length=45)),
                ('match_schedule', models.DateField()),
            ],
            options={
                'db_table': 'user_match_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=45)),
                ('team_code', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'user_team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V2_MatchInfo',
            fields=[
                ('v2_match_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('v2_match_host', models.CharField(blank=True, max_length=45, null=True)),
                ('v2_match_location', models.CharField(blank=True, max_length=45, null=True)),
                ('v2_match_home', models.CharField(max_length=45)),
                ('v2_match_away', models.CharField(max_length=45)),
                ('v2_match_result', models.JSONField(blank=True, null=True)),
                ('v2_match_schedule', models.CharField(default=None, max_length=45)),
                ('v2_match_players', models.JSONField(blank=True, null=True)),
                ('v2_match_goalplayers', models.JSONField(blank=True, null=True)),
                ('v2_match_GPSplayers', models.JSONField(blank=True, null=True)),
                ('v2_match_teamcode', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'V2_match_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V2_TeamInfo',
            fields=[
                ('v2_team_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('v2_team_host', models.CharField(blank=True, max_length=45, null=True)),
                ('v2_team_players', models.JSONField(blank=True, null=True)),
                ('v2_team_logo', models.CharField(blank=True, max_length=200, null=True)),
                ('v2_team_name', models.CharField(max_length=45)),
                ('v2_team_match', models.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'V2_team_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VideoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_code', models.CharField(blank=True, max_length=45, null=True)),
                ('user_code', models.CharField(blank=True, max_length=45, null=True)),
                ('quarter_name', models.CharField(blank=True, max_length=45, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(max_length=45)),
                ('date', models.DateField()),
                ('path', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'video_info',
                'managed': False,
            },
        ),
    ]
