# Generated by Django 4.0.3 on 2025-08-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='V3_User',
            fields=[
                ('user_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=200)),
                ('login_type', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'v3_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V3_User_info',
            fields=[
                ('user_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('birth', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('gender', models.CharField(max_length=45)),
                ('marketing_agree', models.BooleanField(default=0)),
                ('user_type', models.CharField(max_length=45)),
                ('level', models.CharField(max_length=45)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('preferred_position', models.CharField(max_length=45)),
                ('activity_area', models.CharField(max_length=45)),
                ('ai_type', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'v3_user_info',
                'managed': False,
            },
        ),
    ]
