# Generated by Django 5.0.1 on 2024-02-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0002_delete_homeuserinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueInfo',
            fields=[
                ('league_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('league_host', models.CharField(max_length=45)),
                ('league_name', models.CharField(max_length=45)),
                ('league_startdate', models.CharField(max_length=45)),
                ('league_enddate', models.CharField(max_length=45)),
                ('league_startjoin', models.CharField(max_length=45)),
                ('league_endjoin', models.CharField(max_length=45)),
                ('league_team', models.JSONField()),
                ('league_area', models.CharField(blank=True, max_length=45, null=True)),
                ('league_logo', models.CharField(blank=True, max_length=45, null=True)),
                ('league_winner', models.CharField(blank=True, max_length=45, null=True)),
                ('league_gametype', models.CharField(max_length=45)),
                ('league_official', models.CharField(max_length=45)),
                ('league_description', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'league_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MatchInfo',
            fields=[
                ('match_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('match_host', models.CharField(max_length=45)),
                ('match_home', models.CharField(max_length=45)),
                ('match_away', models.CharField(max_length=45)),
                ('match_home_player', models.JSONField()),
                ('match_away_player', models.JSONField()),
                ('match_home_result', models.IntegerField()),
                ('match_away_result', models.IntegerField()),
                ('match_total_result', models.JSONField()),
                ('match_official', models.CharField(max_length=45)),
                ('match_starttime', models.CharField(max_length=45)),
                ('match_type', models.JSONField()),
                ('match_goal', models.JSONField(null=True)),
            ],
            options={
                'db_table': 'match_info',
                'managed': False,
            },
        ),
    ]
