# Generated by Django 4.0.3 on 2025-08-26 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0003_v3_player_anal_v3_player_match_cross_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='v3_player_match_quarter_cross',
            table='v3_player_match_quarter_code_cross',
        ),
    ]
