# Generated by Django 4.0.3 on 2025-08-26 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0004_alter_v3_player_match_quarter_cross_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='v3_player_match_quarter_cross',
            table='v3_player_match_quarter_cross',
        ),
    ]
