# Generated by Django 4.0.3 on 2025-08-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0005_alter_v3_player_match_quarter_cross_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='V3_Player_Match',
            fields=[
                ('match_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('grounds_code', models.CharField(max_length=45)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('name', models.CharField(max_length=45)),
                ('standard', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'v3_player_match',
                'managed': False,
            },
        ),
    ]
