# Generated by Django 4.0.3 on 2025-08-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0006_v3_player_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='V3_Player_ai',
            fields=[
                ('match_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('answer', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'v3_player_ai',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V3_Player_quarter',
            fields=[
                ('quarter_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(max_length=45)),
                ('home', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'v3_player_quarter',
                'managed': False,
            },
        ),
    ]
