# Generated by Django 4.0.3 on 2025-08-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0007_v3_player_ai_v3_player_quarter'),
    ]

    operations = [
        migrations.CreateModel(
            name='V3_Ground_info',
            fields=[
                ('ground_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('who_make', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('corner_gps', models.JSONField(blank=True, null=True)),
                ('corner_utm', models.JSONField(blank=True, null=True)),
                ('center', models.JSONField(blank=True, null=True)),
                ('long_side_length', models.FloatField(blank=True, null=True)),
                ('short_side_length', models.FloatField(blank=True, null=True)),
                ('rotate_deg', models.FloatField(blank=True, null=True)),
                ('rotated_corners', models.JSONField(blank=True, null=True)),
                ('new_long', models.FloatField(blank=True, null=True)),
                ('new_short', models.FloatField(blank=True, null=True)),
                ('north_side_utm', models.JSONField(blank=True, null=True)),
                ('south_side_utm', models.JSONField(blank=True, null=True)),
                ('east_side_utm', models.JSONField(blank=True, null=True)),
                ('west_side_utm', models.JSONField(blank=True, null=True)),
                ('who_add', models.CharField(max_length=45)),
                ('who_update', models.CharField(max_length=45)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'v3_player_ai',
                'managed': False,
            },
        ),
    ]
