# Generated by Django 4.0.3 on 2025-08-27 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0008_v3_ground_info'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='v3_ground_info',
            table='v3_ground_info',
        ),
    ]
