# Generated by Django 4.0.3 on 2025-09-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0009_alter_v3_ground_info_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='V3_Player_Video',
            fields=[
                ('video_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('folder_code', models.CharField(max_length=45)),
                ('quarter_code', models.CharField(max_length=45)),
                ('url', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'v3_player_video',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V3_Player_Video_Folder',
            fields=[
                ('folder_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('user_code', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'v3_player_video_folder',
                'managed': False,
            },
        ),
    ]
