# Generated by Django 4.0.3 on 2025-09-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0010_v3_player_video_v3_player_video_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='V3_Team_Info',
            fields=[
                ('team_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('local', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'v3_player_ai',
                'managed': False,
            },
        ),
    ]
