# Generated by Django 4.0.3 on 2025-09-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0011_v3_team_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='V3_Player_Team_Cross',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_code', models.CharField(max_length=45)),
                ('team_code', models.CharField(max_length=45)),
                ('role', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'v3_player_team_cross',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V3_Team_Join_Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_code', models.CharField(max_length=45, verbose_name='팀 코드')),
                ('user_code', models.CharField(max_length=45, verbose_name='유저 코드')),
                ('request_type', models.CharField(choices=[('player_to_team', '선수가 팀에 가입 신청'), ('team_to_player', '팀이 선수에게 영입 제안')], max_length=20, verbose_name='요청 타입')),
                ('status', models.CharField(choices=[('pending', '대기중'), ('accepted', '수락됨'), ('rejected', '거절됨'), ('cancelled', '취소됨')], default='pending', max_length=20, verbose_name='상태')),
                ('message', models.TextField(blank=True, null=True, verbose_name='메시지')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='요청 시간')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='응답 시간')),
                ('responded_by', models.CharField(blank=True, max_length=45, null=True, verbose_name='응답자')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'V3 팀 가입 요청',
                'verbose_name_plural': 'V3 팀 가입 요청들',
                'db_table': 'v3_team_join_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='V3_Team_Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipient_code', models.CharField(max_length=45, verbose_name='수신자 코드')),
                ('sender_code', models.CharField(blank=True, max_length=45, null=True, verbose_name='발신자 코드')),
                ('team_code', models.CharField(max_length=45, verbose_name='팀 코드')),
                ('notification_type', models.CharField(choices=[('join_request', '가입 신청'), ('join_accepted', '가입 수락'), ('join_rejected', '가입 거절'), ('team_invite', '팀 초대'), ('invite_accepted', '초대 수락'), ('invite_rejected', '초대 거절'), ('member_left', '멤버 탈퇴'), ('member_kicked', '멤버 추방')], max_length=20, verbose_name='알림 타입')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('message', models.TextField(verbose_name='메시지')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음 여부')),
                ('related_request_id', models.IntegerField(blank=True, null=True, verbose_name='관련 요청 ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='읽은 시간')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'V3 팀 알림',
                'verbose_name_plural': 'V3 팀 알림들',
                'db_table': 'v3_team_notification',
                'managed': False,
            },
        ),
    ]
