# Generated by Django 4.0.3 on 2025-09-01 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0012_v3_player_team_cross_v3_team_join_request_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='v3_team_join_request',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='v3_team_notification',
            options={'managed': False},
        ),
        migrations.AlterModelTable(
            name='v3_team_info',
            table='v3_team_info',
        ),
    ]
