# Generated by Django 4.0.3 on 2025-09-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0014_playerai_playeranal_playermatch_playermatchcross_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipient_code', models.CharField(max_length=45)),
                ('sender_code', models.CharField(blank=True, max_length=45, null=True)),
                ('category', models.CharField(choices=[('team', '팀'), ('analysis', '분석'), ('system', '시스템'), ('event', '이벤트'), ('social', '소셜'), ('achievement', '성취')], max_length=20)),
                ('notification_type', models.CharField(choices=[('team_join_request', '팀 가입 신청'), ('team_join_accepted', '팀 가입 수락'), ('team_join_rejected', '팀 가입 거절'), ('team_invite_sent', '팀 초대 발송'), ('team_invite_received', '팀 초대 수신'), ('team_invite_accepted', '팀 초대 수락'), ('team_invite_rejected', '팀 초대 거절'), ('team_member_joined', '팀 멤버 가입'), ('team_member_left', '팀 멤버 탈퇴'), ('team_member_kicked', '팀 멤버 추방'), ('team_role_changed', '팀 역할 변경'), ('team_created', '팀 생성'), ('team_updated', '팀 정보 수정'), ('analysis_completed', '분석 완료'), ('analysis_failed', '분석 실패'), ('performance_report', '성능 리포트'), ('weekly_summary', '주간 요약'), ('monthly_summary', '월간 요약'), ('system_maintenance', '시스템 점검'), ('app_update', '앱 업데이트'), ('feature_announcement', '기능 공지'), ('service_notice', '서비스 공지'), ('account_security', '계정 보안'), ('event_start', '이벤트 시작'), ('event_end', '이벤트 종료'), ('event_reward', '이벤트 보상'), ('friend_request', '친구 요청'), ('friend_accepted', '친구 수락'), ('player_follow', '플레이어 팔로우'), ('mention', '멘션'), ('goal_achieved', '목표 달성'), ('milestone_reached', '마일스톤 달성'), ('badge_earned', '배지 획득'), ('level_up', '레벨 업'), ('record_broken', '기록 갱신')], max_length=30)),
                ('priority', models.CharField(choices=[('low', '낮음'), ('normal', '보통'), ('high', '높음'), ('urgent', '긴급'), ('critical', '중요')], default='normal', max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('short_message', models.CharField(blank=True, max_length=50, null=True)),
                ('related_data', models.JSONField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notification',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamAi',
            fields=[
                ('match_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('answer', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'team_ai',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamAnal',
            fields=[
                ('quarter_code', models.IntegerField(primary_key=True, serialize=False)),
                ('team_analcol', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'team_anal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMatchQuarterCross',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('match_code', models.CharField(max_length=45)),
                ('quarter_code', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'team_match_quarter_cross',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamQuarter',
            fields=[
                ('quarter_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('home', models.CharField(choices=[('west', 'West'), ('east', 'East')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'team_quarter',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='TeamMatchQuaterCross',
        ),
        migrations.DeleteModel(
            name='TeamNotification',
        ),
        migrations.DeleteModel(
            name='TeamQuater',
        ),
    ]
