# Generated by Django 4.0.3 on 2025-10-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DB', '0015_notification_teamai_teamanal_teammatchquartercross_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBoard',
            fields=[
                ('content_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('event', 'Event'), ('notice', 'Notice'), ('inquiry', 'Inquiry')], max_length=45)),
                ('author_code', models.CharField(max_length=45)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('thumbnail_url', models.CharField(blank=True, max_length=500, null=True)),
                ('image_urls', models.JSONField(blank=True, null=True)),
                ('attachment_urls', models.JSONField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('event_start_date', models.DateTimeField(blank=True, null=True)),
                ('event_end_date', models.DateTimeField(blank=True, null=True)),
                ('event_link', models.CharField(blank=True, max_length=500, null=True)),
                ('event_reward', models.CharField(blank=True, max_length=200, null=True)),
                ('event_conditions', models.JSONField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], max_length=45, null=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('notice_start_date', models.DateTimeField(blank=True, null=True)),
                ('notice_end_date', models.DateTimeField(blank=True, null=True)),
                ('inquiry_type', models.CharField(blank=True, choices=[('account', 'Account'), ('payment', 'Payment'), ('match_analysis', 'Match Analysis'), ('team', 'Team'), ('ground', 'Ground'), ('app_feature', 'App Feature'), ('bug_report', 'Bug Report'), ('suggestion', 'Suggestion'), ('other', 'Other')], max_length=45, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('rejected', 'Rejected')], max_length=45, null=True)),
                ('related_match_code', models.CharField(blank=True, max_length=45, null=True)),
                ('related_quarter_code', models.CharField(blank=True, max_length=45, null=True)),
                ('related_team_code', models.CharField(blank=True, max_length=45, null=True)),
                ('related_ground_code', models.CharField(blank=True, max_length=45, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('answered_by', models.CharField(blank=True, max_length=45, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('is_private', models.BooleanField(default=True)),
                ('target_user_type', models.CharField(blank=True, choices=[('all', 'All'), ('player', 'Player'), ('coach', 'Coach'), ('parents', 'Parents'), ('youth', 'Youth'), ('adult', 'Adult'), ('pro', 'Pro')], default='all', max_length=45, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'content_board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContentComment',
            fields=[
                ('comment_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('content_code', models.CharField(max_length=45)),
                ('user_code', models.CharField(max_length=45)),
                ('comment', models.TextField()),
                ('parent_comment_code', models.CharField(blank=True, max_length=45, null=True)),
                ('like_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'content_comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContentEventParticipation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content_code', models.CharField(max_length=45)),
                ('user_code', models.CharField(max_length=45)),
                ('is_completed', models.BooleanField(default=False)),
                ('reward_received', models.BooleanField(default=False)),
                ('participation_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'content_event_participation',
                'managed': False,
            },
        ),
    ]
