# Generated by Django 3.2.23 on 2023-12-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('user_pw', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='emaillist',
        ),
    ]
