# Generated by Django 3.2.23 on 2023-12-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20231231_0126'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalGame',
            fields=[
                ('anal_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('anal_game_code', models.CharField(max_length=45)),
                ('anal_gps_code', models.CharField(max_length=45)),
                ('anal_team_code', models.CharField(max_length=45)),
                ('anal_result', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'anal_game',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AnalPlayer',
            fields=[
                ('anal_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('anal_gps_code', models.CharField(max_length=45)),
                ('anal_player_code', models.CharField(max_length=45)),
                ('anal_result', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'anal_player',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ARank',
            fields=[
                ('a_team_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('a_team_score', models.CharField(max_length=45)),
                ('a_update_time', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'a_rank',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameGps',
            fields=[
                ('gps_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('gps_game_code', models.CharField(max_length=45)),
                ('gps_team_code', models.CharField(max_length=45)),
                ('gps_player_code', models.CharField(max_length=45)),
                ('gps_device_code', models.CharField(max_length=45)),
                ('gps_time', models.CharField(max_length=45)),
                ('gps_lat', models.CharField(max_length=45)),
                ('gps_lon', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'game_gps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GameInfo',
            fields=[
                ('game_code', models.IntegerField(primary_key=True, serialize=False)),
                ('game_home_team', models.CharField(max_length=45)),
                ('game_away_team', models.CharField(max_length=45)),
                ('game_home_player', models.CharField(max_length=45)),
                ('game_away_player', models.CharField(max_length=45)),
                ('game_home_result', models.CharField(max_length=45)),
                ('game_away_result', models.CharField(max_length=45)),
                ('game_type', models.CharField(max_length=45)),
                ('game_time', models.CharField(max_length=45)),
                ('game_place', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'game_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HomeUserInfo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_code', models.CharField(max_length=50)),
                ('user_id', models.CharField(max_length=50)),
                ('user_pw', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'home_user_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TeamInfo',
            fields=[
                ('team_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=45)),
                ('team_host', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'team_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=45)),
                ('user_pw', models.CharField(max_length=45)),
                ('user_birth', models.CharField(max_length=45)),
                ('user_name', models.CharField(max_length=45)),
                ('user_gender', models.CharField(max_length=45)),
                ('user_email', models.CharField(max_length=45)),
                ('user_team', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'user_info',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='user_info',
        ),
    ]
