# Generated by Django 3.2.23 on 2023-12-30 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20231231_0139'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalGame',
        ),
        migrations.DeleteModel(
            name='AnalPlayer',
        ),
        migrations.DeleteModel(
            name='ARank',
        ),
        migrations.DeleteModel(
            name='GameGps',
        ),
        migrations.DeleteModel(
            name='GameInfo',
        ),
        migrations.DeleteModel(
            name='HomeUserInfo',
        ),
        migrations.DeleteModel(
            name='TeamInfo',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
