# Generated by Django 3.2.23 on 2023-12-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_auto_20231231_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('user_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=45)),
            ],
        ),
    ]
