# Generated by Django 3.2.23 on 2023-12-31 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'managed': False},
        ),
    ]
