# Generated by Django 3.2.23 on 2023-12-31 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='user_info',
        ),
    ]
