# Generated by Django 4.0.3 on 2024-10-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestAnalyzeData',
            fields=[
                ('anal_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('match_code', models.CharField(default='m_000', max_length=45)),
                ('user_code', models.CharField(default='u_000', max_length=45)),
                ('user_id', models.CharField(default='000000', max_length=45)),
                ('match_date', models.CharField(default='20000101', max_length=20)),
                ('match_number', models.IntegerField(default=0)),
                ('quarter', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'test_analyze_data',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TestUserInfo',
            fields=[
                ('user_code', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=45)),
                ('user_type', models.CharField(default='player', max_length=20)),
                ('user_position', models.CharField(blank=True, max_length=45)),
                ('team_players', models.JSONField()),
            ],
            options={
                'db_table': 'test_user_info',
                'managed': True,
            },
        ),
    ]
