# Generated by Django 4.0.3 on 2024-10-28 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testanalyzedata',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='testuserinfo',
            options={'managed': False},
        ),
    ]
